'''empty message

Revision ID: 00eea3b54f6c
Revises: 255d97230d20
Create Date: 2020-06-06 18:56:55.521111

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00eea3b54f6c'
down_revision = '255d97230d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('attendancecheck', sa.Boolean(), nullable=True))
    op.execute('UPDATE event SET attendancecheck = true')

    op.add_column('meeting', sa.Column('attendancecheck', sa.Boolean(), nullable=True))
    op.execute('UPDATE meeting SET attendancecheck = true')

    op.add_column('user', sa.Column('eventAlertoneday', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('eventAlertoneweek', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('eventAlertthreeday', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('meetingAlertoneday', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('meetingAlertoneweek', sa.Boolean(), nullable=True)) 
    op.add_column('user', sa.Column('meetingAlertthreeday', sa.Boolean(), nullable=True))

    #op.execute('UPDATE user SET meetingAlertoneday = false, eventAlertoneweek = false, meetingAlertthreeday = false, meetingAlertthreeday = false, meetingAlertoneweek = false, meetingAlertoneday = false')

    #op.alter_column('user', 'meetingAlertoneday', nullable=False)
    #op.alter_column('user', 'meetingAlertoneweek', nullable=False)
    #op.alter_column('user', 'eventAlertthreeday', nullable=False)
    #op.alter_column('user', 'eventAlertoneweek', nullable=False)
    #op.alter_column('user', 'eventAlertoneday', nullable=False)
    #op.alter_column('user', 'meetingAlertthreeday', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'meetingAlertthreeday')
    op.drop_column('user', 'meetingAlertoneweek')
    op.drop_column('user', 'meetingAlertoneday')
    op.drop_column('user', 'eventAlertthreeday')
    op.drop_column('user', 'eventAlertoneweek')
    op.drop_column('user', 'eventAlertoneday')
    op.drop_column('meeting', 'attendancecheck')
    op.drop_column('event', 'attendancecheck')
    # ### end Alembic commands ###
