'''empty message

Revision ID: 00eea3b54f6c
Revises: 255d97230d20
Create Date: 2020-06-06 18:56:55.521111

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00eea3b54f6c'
down_revision = '255d97230d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('attendancecheck', sa.Boolean(), nullable=True))
    op.execute('UPDATE event SET attendancecheck = true')

    op.add_column('meeting', sa.Column('attendancecheck', sa.Boolean(), nullable=True))
    op.execute('UPDATE meeting SET attendancecheck = true')

    op.add_column('user', sa.Column('eventAlert1day', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('eventAlert1week', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('eventAlert3day', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('meetingAlert1day', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('meetingAlert1week', sa.Boolean(), nullable=True)) 
    op.add_column('user', sa.Column('meetingAlert3day', sa.Boolean(), nullable=True))

    op.execute('UPDATE user SET eventAlert1day = false, eventAlert1week = false, eventAlert3day = false, meetingAlert3day = false, meetingAlert1week = false, meetingAlert1day = false')

    op.alter_column('user', 'meetingAlert1day', nullable=False)
    op.alter_column('user', 'meetingAlert1week', nullable=False)
    op.alter_column('user', 'eventAlert3day', nullable=False)
    op.alter_column('user', 'eventAlert1week', nullable=False)
    op.alter_column('user', 'eventAlert1day', nullable=False)
    op.alter_column('user', 'meetingAlert3day', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'meetingAlert3day')
    op.drop_column('user', 'meetingAlert1week')
    op.drop_column('user', 'meetingAlert1day')
    op.drop_column('user', 'eventAlert3day')
    op.drop_column('user', 'eventAlert1week')
    op.drop_column('user', 'eventAlert1day')
    op.drop_column('meeting', 'attendancecheck')
    op.drop_column('event', 'attendancecheck')
    # ### end Alembic commands ###
