"""empty message

Revision ID: 01fcbe4d3eb5
Revises: ae414864725a
Create Date: 2020-05-17 09:59:32.598474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01fcbe4d3eb5'
down_revision = 'ae414864725a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event', ['id'])
    op.create_unique_constraint(None, 'meeting', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.add_column('user_event', sa.Column('currentYear', sa.Boolean(), nullable=True))
    op.add_column('user_meeting', sa.Column('currentYear', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_meeting', 'currentYear')
    op.drop_column('user_event', 'currentYear')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'meeting', type_='unique')
    op.drop_constraint(None, 'event', type_='unique')
    # ### end Alembic commands ###
