"""empty message

Revision ID: 03e41ac7ecf7
Revises: 4222db9d440b
Create Date: 2020-02-26 07:49:34.087402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03e41ac7ecf7'
down_revision = '4222db9d440b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registered')
    op.add_column('user_event', sa.Column('hourcount', sa.Float(), nullable=False))
    op.add_column('user_meeting', sa.Column('hourcount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_meeting', 'hourcount')
    op.drop_column('user_event', 'hourcount')
    op.add_column('user', sa.Column('registered', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
