"""empty message

Revision ID: 0ea4b06625ac
Revises: e5dc3d0512ee
Create Date: 2020-02-26 13:30:06.993107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea4b06625ac'
down_revision = 'e5dc3d0512ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('leader', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'leader')
    # ### end Alembic commands ###
