"""empty message

Revision ID: 15a778233001
Revises: 9ed4d9416108
Create Date: 2020-06-02 19:13:15.782875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a778233001'
down_revision = '9ed4d9416108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event', ['id'])
    op.create_unique_constraint(None, 'meeting', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'meeting', type_='unique')
    op.drop_constraint(None, 'event', type_='unique')
    # ### end Alembic commands ###
