"""empty message

Revision ID: 19fdd0dbb308
Revises: 43cfabe42752
Create Date: 2020-03-04 21:58:00.404622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fdd0dbb308'
down_revision = '43cfabe42752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('location', sa.String(length=150), nullable=True))
    op.add_column('meeting', sa.Column('location', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'location')
    op.drop_column('event', 'location')
    # ### end Alembic commands ###
