"""empty message

Revision ID: 227d93dff907
Revises: 52ce4bbd0df4
Create Date: 2020-05-22 15:34:15.360893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227d93dff907'
down_revision = '52ce4bbd0df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('goal', sa.String(length=500), nullable=True))
    op.drop_column('group', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('group', 'goal')
    # ### end Alembic commands ###
