"""empty message

Revision ID: 255d97230d20
Revises: 2fff815eced5
Create Date: 2020-06-04 02:01:42.236392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255d97230d20'
down_revision = '2fff815eced5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('attendancecount', sa.Integer(), nullable=True))
    op.add_column('meeting', sa.Column('attendancecount', sa.Integer(), nullable=True))
    op.execute("UPDATE event SET attendancecount = 0")
    op.execute("UPDATE meeting SET attendancecount = 0")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'attendancecount')
    op.drop_column('event', 'attendancecount')
    # ### end Alembic commands ###
