"""empty message
Revision ID: 2836c70897ee
Revises: 
Create Date: 2020-02-23 18:11:18.999833
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2836c70897ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###