"""empty message

Revision ID: 2fff815eced5
Revises: 4c5fcef80038
Create Date: 2020-06-04 01:47:52.656789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fff815eced5'
down_revision = '4c5fcef80038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'showaddr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('showaddr', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
