"""empty message

Revision ID: 39191dcd419c
Revises: 8b7bbe91ca68
Create Date: 2020-05-21 10:31:51.787569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39191dcd419c'
down_revision = '8b7bbe91ca68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event', ['id'])
    op.create_unique_constraint(None, 'meeting', ['id'])
    op.add_column('user', sa.Column('phoneareacode', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('phoneend', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('phonemiddle', sa.Integer(), nullable=True))
    op.drop_constraint('user_phone1_key', 'user', type_='unique')
    op.drop_constraint('user_phone2_key', 'user', type_='unique')
    op.drop_constraint('user_phone3_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user', ['phoneareacode'])
    op.create_unique_constraint(None, 'user', ['phonemiddle'])
    op.create_unique_constraint(None, 'user', ['phoneend'])
    op.drop_column('user', 'phone3')
    op.drop_column('user', 'phone1')
    op.drop_column('user', 'phone2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('phone1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('phone3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_phone3_key', 'user', ['phone3'])
    op.create_unique_constraint('user_phone2_key', 'user', ['phone2'])
    op.create_unique_constraint('user_phone1_key', 'user', ['phone1'])
    op.drop_column('user', 'phonemiddle')
    op.drop_column('user', 'phoneend')
    op.drop_column('user', 'phoneareacode')
    op.drop_constraint(None, 'meeting', type_='unique')
    op.drop_constraint(None, 'event', type_='unique')
    # ### end Alembic commands ###
