"""empty message

Revision ID: 4222db9d440b
Revises: 376a0e7ebd21
Create Date: 2020-02-25 21:24:19.100756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4222db9d440b'
down_revision = '376a0e7ebd21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_meeting')
    op.add_column('event', sa.Column('hourcount', sa.Float(), nullable=False))
    op.add_column('meeting', sa.Column('hourcount', sa.Float(), nullable=False))
    op.add_column('user', sa.Column('namecount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'namecount')
    op.drop_column('meeting', 'hourcount')
    op.drop_column('event', 'hourcount')
    op.create_table('event_meeting',
    sa.Column('eventid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('length', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['eventid'], ['event.id'], name='event_meeting_eventid_fkey'),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], name='event_meeting_userid_fkey'),
    sa.PrimaryKeyConstraint('eventid', 'userid', name='event_meeting_pkey')
    )
    # ### end Alembic commands ###
