"""empty message

Revision ID: 438e81d3145a
Revises: d8f20cc69b0c
Create Date: 2020-05-21 00:44:51.636426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438e81d3145a'
down_revision = 'd8f20cc69b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event', ['id'])
    op.create_unique_constraint(None, 'meeting', ['id'])
    op.add_column('user', sa.Column('phonenumber', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('showemail', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('showphone', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'user', ['phonenumber'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'showphone')
    op.drop_column('user', 'showemail')
    op.drop_column('user', 'phonenumber')
    op.drop_constraint(None, 'meeting', type_='unique')
    op.drop_constraint(None, 'event', type_='unique')
    # ### end Alembic commands ###
