"""empty message

Revision ID: 43cfabe42752
Revises: 782c4eef1834
Create Date: 2020-03-04 21:44:56.646592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cfabe42752'
down_revision = '782c4eef1834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_event', sa.Column('attended', sa.Boolean(), nullable=True))
    op.add_column('user_event', sa.Column('comment', sa.String(length=500), nullable=True))
    op.add_column('user_event', sa.Column('downvote', sa.Boolean(), nullable=True))
    op.add_column('user_event', sa.Column('going', sa.Boolean(), nullable=True))
    op.add_column('user_event', sa.Column('unsurevote', sa.Boolean(), nullable=True))
    op.add_column('user_event', sa.Column('upvote', sa.Boolean(), nullable=True))
    op.add_column('user_meeting', sa.Column('attended', sa.Boolean(), nullable=True))
    op.add_column('user_meeting', sa.Column('comment', sa.String(length=500), nullable=True))
    op.add_column('user_meeting', sa.Column('downvote', sa.Boolean(), nullable=True))
    op.add_column('user_meeting', sa.Column('going', sa.Boolean(), nullable=True))
    op.add_column('user_meeting', sa.Column('unsurevote', sa.Boolean(), nullable=True))
    op.add_column('user_meeting', sa.Column('upvote', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_meeting', 'upvote')
    op.drop_column('user_meeting', 'unsurevote')
    op.drop_column('user_meeting', 'going')
    op.drop_column('user_meeting', 'downvote')
    op.drop_column('user_meeting', 'comment')
    op.drop_column('user_meeting', 'attended')
    op.drop_column('user_event', 'upvote')
    op.drop_column('user_event', 'unsurevote')
    op.drop_column('user_event', 'going')
    op.drop_column('user_event', 'downvote')
    op.drop_column('user_event', 'comment')
    op.drop_column('user_event', 'attended')
    # ### end Alembic commands ###
