"""empty message

Revision ID: 4c5fcef80038
Revises: 15a778233001
Create Date: 2020-06-03 13:19:05.780775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5fcef80038'
down_revision = '15a778233001'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
