"""empty message

Revision ID: 500a28fe840f
Revises: 03e41ac7ecf7
Create Date: 2020-02-26 07:59:07.377838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500a28fe840f'
down_revision = '03e41ac7ecf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'length')
    op.drop_column('user', 'leader')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('leader', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('meeting', sa.Column('length', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
