"""empty message

Revision ID: 7a64de4cccb7
Revises: 438e81d3145a
Create Date: 2020-05-21 10:22:48.429487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a64de4cccb7'
down_revision = '438e81d3145a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event', ['id'])
    op.create_unique_constraint(None, 'meeting', ['id'])
    op.add_column('user', sa.Column('areacode', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('phone2', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('phone3', sa.Integer(), nullable=True))
    op.drop_constraint('user_phonenumber_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user', ['areacode'])
    op.create_unique_constraint(None, 'user', ['phone2'])
    op.create_unique_constraint(None, 'user', ['phone3'])
    op.drop_column('user', 'phonenumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phonenumber', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_phonenumber_key', 'user', ['phonenumber'])
    op.drop_column('user', 'phone3')
    op.drop_column('user', 'phone2')
    op.drop_column('user', 'areacode')
    op.drop_constraint(None, 'meeting', type_='unique')
    op.drop_constraint(None, 'event', type_='unique')
    # ### end Alembic commands ###
