"""empty message

Revision ID: 8b7bbe91ca68
Revises: 7a64de4cccb7
Create Date: 2020-05-21 10:27:29.437805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7bbe91ca68'
down_revision = '7a64de4cccb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event', ['id'])
    op.create_unique_constraint(None, 'meeting', ['id'])
    op.add_column('user', sa.Column('phone1', sa.Integer(), nullable=True))
    op.drop_constraint('user_areacode_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user', ['phone1'])
    op.drop_column('user', 'areacode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('areacode', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_areacode_key', 'user', ['areacode'])
    op.drop_column('user', 'phone1')
    op.drop_constraint(None, 'meeting', type_='unique')
    op.drop_constraint(None, 'event', type_='unique')
    # ### end Alembic commands ###
