"""empty message

Revision ID: 91cd09673e75
Revises: c4dfa1c9635e
Create Date: 2020-10-16 11:06:48.098953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91cd09673e75'
down_revision = 'c4dfa1c9635e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'announcments', ['id'])
    op.create_unique_constraint(None, 'event', ['id'])
    op.create_unique_constraint(None, 'meeting', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'year_audit', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'year_audit', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'meeting', type_='unique')
    op.drop_constraint(None, 'event', type_='unique')
    op.drop_constraint(None, 'announcments', type_='unique')
    # ### end Alembic commands ###
