"""empty message

Revision ID: b27c60e02c92
Revises: 376a0e7ebd21
Create Date: 2020-02-24 20:58:51.318423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27c60e02c92'
down_revision = '376a0e7ebd21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('length', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('hours', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('nicknameapprove', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nicknameapprove')
    op.drop_column('user', 'hours')
    op.drop_column('meeting', 'length')
    # ### end Alembic commands ###
