"""empty message

Revision ID: b2e39840bfb0
Revises: 500a28fe840f
Create Date: 2020-02-26 11:54:48.991901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2e39840bfb0'
down_revision = '500a28fe840f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_event', 'hourcount')
    op.drop_column('user_meeting', 'hourcount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_meeting', sa.Column('hourcount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('user_event', sa.Column('hourcount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
