"""empty message

Revision ID: b39630a0fd86
Revises: 19fdd0dbb308
Create Date: 2020-03-24 13:02:10.519990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b39630a0fd86'
down_revision = '19fdd0dbb308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event', ['id'])
    op.create_unique_constraint(None, 'meeting', ['id'])
    op.add_column('user', sa.Column('currentmember', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('grade', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('school', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'school')
    op.drop_column('user', 'grade')
    op.drop_column('user', 'currentmember')
    op.drop_constraint(None, 'meeting', type_='unique')
    op.drop_constraint(None, 'event', type_='unique')
    # ### end Alembic commands ###
