"""empty message

Revision ID: b4f68010cf06
Revises: 9c09976b59d3
Create Date: 2020-02-23 22:12:05.387964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f68010cf06'
down_revision = '9c09976b59d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('leader', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'leader')
    # ### end Alembic commands ###
