"""empty message

Revision ID: c4dfa1c9635e
Revises: 00eea3b54f6c
Create Date: 2020-06-26 21:42:55.360212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4dfa1c9635e'
down_revision = '00eea3b54f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('alertoneday', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('alertoneweek', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('alertthreeday', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'event', ['id'])
    op.add_column('meeting', sa.Column('alertoneday', sa.Boolean(), nullable=True))
    op.add_column('meeting', sa.Column('alertoneweek', sa.Boolean(), nullable=True))
    op.add_column('meeting', sa.Column('alertthreeday', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'meeting', ['id'])
    op.add_column('user', sa.Column('ingroup', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    op.add_column('user_group', sa.Column('currentYear', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'year_audit', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'year_audit', type_='unique')
    op.drop_column('user_group', 'currentYear')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'ingroup')
    op.drop_constraint(None, 'meeting', type_='unique')
    op.drop_column('meeting', 'alertthreeday')
    op.drop_column('meeting', 'alertoneweek')
    op.drop_column('meeting', 'alertoneday')
    op.drop_constraint(None, 'event', type_='unique')
    op.drop_column('event', 'alertthreeday')
    op.drop_column('event', 'alertoneweek')
    op.drop_column('event', 'alertoneday')
    # ### end Alembic commands ###
