"""empty message

Revision ID: d8f20cc69b0c
Revises: 01fcbe4d3eb5
Create Date: 2020-05-17 14:48:08.907003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f20cc69b0c'
down_revision = '01fcbe4d3eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event', ['id'])
    op.create_unique_constraint(None, 'meeting', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'meeting', type_='unique')
    op.drop_constraint(None, 'event', type_='unique')
    # ### end Alembic commands ###
