"""empty message

Revision ID: e5dc3d0512ee
Revises: b2e39840bfb0
Create Date: 2020-02-26 13:23:32.906697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5dc3d0512ee'
down_revision = 'b2e39840bfb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'name')
    # ### end Alembic commands ###
