"""empty message

Revision ID: f8184878c692
Revises: c42450553bbe
Create Date: 2020-05-05 17:48:04.856100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8184878c692'
down_revision = 'c42450553bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('currentYear', sa.Boolean(), nullable=True))
    op.add_column('meeting', sa.Column('currentYear', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('currentEventHours', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('currentHours', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('currentMeetingHours', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('lifetimeEventHours', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('lifetimeHours', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('lifetimeMeetingHours', sa.Float(), nullable=True))
    op.drop_column('user', 'hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hours', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('user', 'lifetimeMeetingHours')
    op.drop_column('user', 'lifetimeHours')
    op.drop_column('user', 'lifetimeEventHours')
    op.drop_column('user', 'currentMeetingHours')
    op.drop_column('user', 'currentHours')
    op.drop_column('user', 'currentEventHours')
    op.drop_column('meeting', 'currentYear')
    op.drop_column('event', 'currentYear')
    # ### end Alembic commands ###
